site_name: ReMeta API
site_url: https://re-meta.github.io/api/

theme:
  name: "material"
  custom_dir: overrides
  logo: img/logo_api.png
  favicon: img/favicon.svg
  icon:
    repo: custom/github
  palette:
    - scheme: default
      primary: white
  features:
    - navigation.expand
#  features:
#    - navigation.tabs

repo_url: https://github.com/coconeuro/remeta
repo_name: 'GitHub'

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/external-tabs.js

extra:
  generator: false

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      locale: en
      handlers:
        python:
          paths:
            - ..  # include parent directory
          options:
            docstring_style: google   # or numpy
            show_signature_annotations: true
            separate_signature: true
            show_docstring_parameters: true
            show_source: true
            relative_crossrefs: true
            show_bases: false
            show_root_toc_entry: false

nav:
  - ReMeta Guide:
    - → re-meta.github.io ⮺: https://re-meta.github.io
  - API:
    - Plotting: plot.md
    - Simulation: gendata.md
    - Configuration: configuration.md