site_name: ReMeta API
site_url: https://re-meta.github.io/api/

theme:
  name: "material"
  custom_dir: overrides
  logo: img/logo_api.png
  favicon: img/favicon.svg
  icon:
    repo: custom/github
  palette:
    - scheme: default
      primary: white
  features:
    - navigation.expand
#  features:
#    - navigation.tabs

repo_url: https://github.com/coconeuro/remeta
repo_name: 'GitHub'

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/external-tabs.js

extra:
  generator: false

# Currently we need to force-import remeta.configuration via hooks.py, so that griffe correctly
# renders the description fields in the dataclass. This seems like a bug.
hooks:
  - docs/hooks.py

plugins:
  - search
  - autorefs
  - mkdocstrings:
#      custom_templates: templates
      default_handler: python
      locale: en
      handlers:
        python:
          paths:
            - ..  # include parent directory
          options:
            docstring_style: google   # or numpy
            show_signature_annotations: true
#            merge_init_into_class: true
            separate_signature: true
            show_docstring_parameters: true
            show_docstring_attributes: true
            show_source: true
            relative_crossrefs: true
            show_bases: false
            show_root_heading: false
            show_root_toc_entry: false
#            allow_inspection: true
#            force_inspection: true
#            members: false
#            show_if_no_docstring: false   # key
#            inherited_members: false
#            show_root_heading: true
#            show_root_full_path: false
#            members:
#              - classes
#              - functions
            extensions:
              - griffe_fieldz:
                  add_fields_to: docstring-parameters
#                  add_fields_to: docstring-attributes
#                  remove_fields_from_members: true
#                  field_doc_key: doc

nav:
  - → Guide ⮺: https://re-meta.github.io
  - API: index.md
  - ReMeta: model.md
  - Configuration: configuration.md  
  - Parameter: parameter.md
  - Simulation: simulation.md
  - Plotting: plot.md  

# markdown_extensions:
#   - pymdownx.highlight
#   - pymdownx.superfences  